### ISSUE TITLE
Is there any way to test this in debug mode?

### ISSUE THREAD

**Issue by brspurri** [androidmads/UpdateHandler#3]
I'm just looking to test that this works, and don't want to push to Play to see it in action. Is there any way to test when running a debug version?

**Comment by androidmads** [comment]
**You can test this with debug version**.
# Note:
if you have your application is in google play, then it works perfectly to intimate about newer version. if you are not uploaded any version of your application, then it gives update found result is false or provides error log as **_404 response_**.

**Comment by brspurri** [comment]
Indeed, this does work in debug. Just a note for others testing, it appears the `versionCode` of your app must be lower than whats in the app store (I had originally thought `versionName`).
